#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
   :LOGBOOK:
   CLOCK: [2018-05-14 Mon 10:50]--[2018-05-14 Mon 11:02] =>  0:12
   :END:
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

Contrapositive: Switch the hypothesis and conclusion of a conditional statement
 and negating both. ~q->~p

Converse: Switch the hypothesis and conclusion of a conditional statement. q->p

inverse: Negate the hypothesis and conclusion of a conditional statement. ~p->~q

R: real numbers: The set of all numbers including rational and irrational numbers.

Z: integers: All whole numbers.

Q: rational numbers: Any number that can be obtained by dividing two integers.

predicate: A boolean valued function (true, false)

Domain: The set of all possible inputs for a function .

CoDomain: The set of all possible outputs for a function.

quantifier: Indicates the scope of the attatched term.

antecedent: a term that logically precedes another.

consequent: the result of.

Set: A collection of terms with no repeats.

Fallacy: an unsound or mistaken argument or belief

biconditional: if and only if

sufficient condition: if p then q (if p condition is met, then q happens/exists)

necessary condition: if not p then not q (if p condition is not met, then q cannot.

~p: negation

p ^ q: and

p V q: or

p XOR q: exclusive or

p == q: comparison

p -> q: conditional

p <--> q: biconditional

Three dots in a triangle: therefore 

upside down A: all

Backwards E: exists

union: or

intersection: and

Commutative laws: order of operations can be reordered. a + b = b + a

associative laws: terms or factors can be associated in any way. a + (b + c) = (a + b) + c

distributive laws: a(b + c) = ab + ac

identity laws: every thing is identical with itself. a = a

negation laws: the opposite or "not" value

double negative law: the negation of a negation is the original value ~(~p) = p

idempotent laws: logically combining a term with itself will produce the same term. aa = a, a + a = a

universal bound laws: a V u = u, a ^ 0 = 0

De morgan's laws: ~(ab) = ~a + ~b, ~(a + b) = ~a * ~b

absorption laws: a V (a ^ b) = a ^ (a V b) = a

negations of t and c: ~t and ~c

vacuously true: all members of an empty set have a certain property.

Modus Ponens: method of affirming

Modus Tollens: mode that denies by denying

Elimination: valid argument form: if a is not related to b and b is related to c then a is not related to c

Transitivity: Valid Argument form: if a is related to b and b is related to c then a is related to c 
